title: Welcome to my page!
description: Home Page
author: Vignesh Narayanan
github: https://github.com/vigsnar
about: Postdoctoral Research Associate <br> Washington University in St. Louis
disqus_shortname: home
#google_analytics: UA-XXXXXXXX-Y

enableTags: false
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
   # - icon: fa-facebook
   #   link: "#"
   # - icon: fa-twitter
   #   link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/vignesh-narayanan-b5764951/"
    - icon: fa-scholar
      #icon_pack: "ai"
      link: "https://scholar.google.com/citations?user=IXy6vzsAAAAJ&hl=en"
   # - icon: fa-stack-exchange
   #   link: "#"
   # - icon: fa-github
   #   link: "https://github.com/agusmakmun"

#share:
  #twitter_username: github.io
  #fb_appid: 1749788565247320

urls:
    - text: research
      url: /research/
    - text: publications
      url: /publications/
    #- text: XML Feed
    #url: /feed.xml

url: "https://vigsnar.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
